# GitHub Pages用Jekyll設定

# サイト情報
title: "ヨミット"
description: "ヨミットは、スマートフォンでブックマークを保存・管理できるシンプルなアプリです。"
url: "https://tonokokko.github.io/yomitto/"
baseurl: "/yomitto"

# Jekyll設定
markdown: kramdown
highlighter: rouge
theme: minima

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# ナビゲーション
navigation:
  - title: "ホーム"
    url: "/"
  - title: "使い方"
    url: "/usage"
  - title: "プライバシーポリシー"
    url: "/privacy"

# SEO設定
lang: ja
locale: ja_JP

# GitHub Pages設定
safe: true
source: .
destination: ./_site
incremental: false

# 除外ファイル
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 含めるファイル
include:
  - app-ads.txt

# 日本語対応
timezone: Asia/Tokyo
encoding: utf-8 